package com.kaching123.tcr.websvc.api.prepaid;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 3/4/2014 8:12:58 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.io.Serializable;
import java.util.Hashtable;

public class BillPaymentReconciliationResponse implements KvmSerializable, Serializable {
    
    public long resultId;
    public String resultDescription;
    public String batchDate;
    public String batchNumber;
    public int totalRecords;
    public double totalPaymentAmount;
    public double totalFeeAmount;
    public VectorBillPaymentReconciliationDetailItem reconciliationDetail;
    
    public BillPaymentReconciliationResponse(){}
    
    public BillPaymentReconciliationResponse(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("ResultId"))
        {
            Object obj = soapObject.getProperty("ResultId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                resultId = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                resultId = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("ResultDescription"))
        {
            Object obj = soapObject.getProperty("ResultDescription");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                resultDescription = j.toString();
            }else if (obj!= null && obj instanceof String){
                resultDescription = (String) obj;
            }
        }
        if (soapObject.hasProperty("BatchDate"))
        {
            Object obj = soapObject.getProperty("BatchDate");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                batchDate = j.toString();
            }else if (obj!= null && obj instanceof String){
                batchDate = (String) obj;
            }
        }
        if (soapObject.hasProperty("BatchNumber"))
        {
            Object obj = soapObject.getProperty("BatchNumber");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                batchNumber = j.toString();
            }else if (obj!= null && obj instanceof String){
                batchNumber = (String) obj;
            }
        }
        if (soapObject.hasProperty("TotalRecords"))
        {
            Object obj = soapObject.getProperty("TotalRecords");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                totalRecords = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                totalRecords = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("TotalPaymentAmount"))
        {
            Object obj = soapObject.getProperty("TotalPaymentAmount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                totalPaymentAmount = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                totalPaymentAmount = (Double) obj;
            }
        }
        if (soapObject.hasProperty("TotalFeeAmount"))
        {
            Object obj = soapObject.getProperty("TotalFeeAmount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                totalFeeAmount = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                totalFeeAmount = (Double) obj;
            }
        }
        if (soapObject.hasProperty("ReconciliationDetail"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("ReconciliationDetail");
            reconciliationDetail = new VectorBillPaymentReconciliationDetailItem(j);
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return resultId;
            case 1:
                return resultDescription;
            case 2:
                return batchDate;
            case 3:
                return batchNumber;
            case 4:
                return totalRecords;
            case 5:
                return totalPaymentAmount;
            case 6:
                return totalFeeAmount;
            case 7:
                return reconciliationDetail;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 8;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = Long.class;
                info.name = "ResultId";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ResultDescription";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "BatchDate";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "BatchNumber";
                break;
            case 4:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "TotalRecords";
                break;
            case 5:
                info.type = Double.class;
                info.name = "TotalPaymentAmount";
                break;
            case 6:
                info.type = Double.class;
                info.name = "TotalFeeAmount";
                break;
            case 7:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "ReconciliationDetail";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
