package com.kaching123.tcr.websvc.api.prepaid;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 3/4/2014 8:12:58 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.io.Serializable;
import java.util.Hashtable;

public class BillPaymentReconciliationDetailItem implements KvmSerializable, Serializable {
    
    public String trackingNumber;
    public String referenceNumber;
    public double paymentAmount;
    public double feeShare;
    
    public BillPaymentReconciliationDetailItem(){}
    
    public BillPaymentReconciliationDetailItem(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("TrackingNumber"))
        {
            Object obj = soapObject.getProperty("TrackingNumber");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                trackingNumber = j.toString();
            }else if (obj!= null && obj instanceof String){
                trackingNumber = (String) obj;
            }
        }
        if (soapObject.hasProperty("ReferenceNumber"))
        {
            Object obj = soapObject.getProperty("ReferenceNumber");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                referenceNumber = j.toString();
            }else if (obj!= null && obj instanceof String){
                referenceNumber = (String) obj;
            }
        }
        if (soapObject.hasProperty("PaymentAmount"))
        {
            Object obj = soapObject.getProperty("PaymentAmount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                paymentAmount = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                paymentAmount = (Double) obj;
            }
        }
        if (soapObject.hasProperty("FeeShare"))
        {
            Object obj = soapObject.getProperty("FeeShare");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                feeShare = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                feeShare = (Double) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return trackingNumber;
            case 1:
                return referenceNumber;
            case 2:
                return paymentAmount;
            case 3:
                return feeShare;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 4;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "TrackingNumber";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ReferenceNumber";
                break;
            case 2:
                info.type = Double.class;
                info.name = "PaymentAmount";
                break;
            case 3:
                info.type = Double.class;
                info.name = "FeeShare";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
