package com.kaching123.tcr.websvc.api.prepaid;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 3/4/2014 8:12:58 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.io.Serializable;
import java.util.Hashtable;

public class DocumentInquiryResponse extends BalanceResponse implements KvmSerializable, Serializable {
    

    public Document requestedDocument;
    public VectorDocument unpaidDocumentList;
    public double unpaidDocumentListAmount;
    public String responseMessage;
    public DocumentInquiryResponse(){}


    public DocumentInquiryResponse(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("PurchaseId"))
        {
            Object obj = soapObject.getProperty("PurchaseId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                purchaseId = j.toString();
            }else if (obj!= null && obj instanceof String){
                purchaseId = (String) obj;
            }
        }
        if (soapObject.hasProperty("RequestedDocument"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("RequestedDocument");
            requestedDocument =  new Document (j);
            
        }
        if (soapObject.hasProperty("UnpaidDocumentList"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("UnpaidDocumentList");
            unpaidDocumentList = new VectorDocument(j);
        }
        if (soapObject.hasProperty("UnpaidDocumentListAmount"))
        {
            Object obj = soapObject.getProperty("UnpaidDocumentListAmount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                unpaidDocumentListAmount = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                unpaidDocumentListAmount = (Double) obj;
            }
        }
        if (soapObject.hasProperty("ResponseMessage"))
        {
            Object obj = soapObject.getProperty("ResponseMessage");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                responseMessage = j.toString();
            }else if (obj!= null && obj instanceof String){
                responseMessage = (String) obj;
            }
        }
        if (soapObject.hasProperty("Timestamp"))
        {
            Object obj = soapObject.getProperty("Timestamp");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                timestamp = j.toString();
            }else if (obj!= null && obj instanceof String){
                timestamp = (String) obj;
            }
        }
        if (soapObject.hasProperty("ResponseCode"))
        {
            Object obj = soapObject.getProperty("ResponseCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                responseCode = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                responseCode = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("ResponseDescription"))
        {
            Object obj = soapObject.getProperty("ResponseDescription");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                responseDescription = j.toString();
            }else if (obj!= null && obj instanceof String){
                responseDescription = (String) obj;
            }
        }
        if (soapObject.hasProperty("ReferenceNumber"))
        {
            Object obj = soapObject.getProperty("ReferenceNumber");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                referenceNumber = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                referenceNumber = (Integer) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return purchaseId;
            case 1:
                return requestedDocument;
            case 2:
                return unpaidDocumentList;
            case 3:
                return unpaidDocumentListAmount;
            case 4:
                return responseMessage;
            case 5:
                return timestamp;
            case 6:
                return responseCode;
            case 7:
                return responseDescription;
            case 8:
                return referenceNumber;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 9;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "PurchaseId";
                break;
            case 1:
                info.type = Document.class;
                info.name = "RequestedDocument";
                break;
            case 2:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "UnpaidDocumentList";
                break;
            case 3:
                info.type = Double.class;
                info.name = "UnpaidDocumentListAmount";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ResponseMessage";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Timestamp";
                break;
            case 6:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "ResponseCode";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ResponseDescription";
                break;
            case 8:
                info.type = Long.class;
                info.name = "ReferenceNumber";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
