package com.kaching123.tcr.websvc.api.prepaid;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 3/4/2014 8:12:58 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.io.Serializable;
import java.util.Hashtable;

public class Document implements KvmSerializable, Serializable {
    
    public String documentId;
    public double documentPaymentAmount;
    
    public Document(){}
    
    public Document(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("DocumentId"))
        {
            Object obj = soapObject.getProperty("DocumentId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                documentId = j.toString();
            }else if (obj!= null && obj instanceof String){
                documentId = (String) obj;
            }
        }
        if (soapObject.hasProperty("DocumentPaymentAmount"))
        {
            Object obj = soapObject.getProperty("DocumentPaymentAmount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                documentPaymentAmount = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                documentPaymentAmount = (Double) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return documentId;
            case 1:
                return documentPaymentAmount;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 2;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "DocumentId";
                break;
            case 1:
                info.type = Double.class;
                info.name = "DocumentPaymentAmount";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
