package com.kaching123.tcr.websvc.api.prepaid;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/25/2015 9:58:59 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.io.Serializable;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import com.kaching123.tcr.websvc.api.prepaid.WS_Enums.SoapProtocolVersion.ResponseStatus;

public class IVULotoResponseData implements KvmSerializable , Serializable {
    
    public String ivuLoto;
    public String controlNumber;
    public String drawNumber;
    public String drawDate;
    public ResponseStatus status;
    public String errorDetail;
    
    public IVULotoResponseData(){}
    
    public IVULotoResponseData(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("IvuLoto"))
        {
            Object obj = soapObject.getProperty("IvuLoto");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                ivuLoto = j.toString();
            }else if (obj!= null && obj instanceof String){
                ivuLoto = (String) obj;
            }
        }
        if (soapObject.hasProperty("ControlNumber"))
        {
            Object obj = soapObject.getProperty("ControlNumber");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                controlNumber = j.toString();
            }else if (obj!= null && obj instanceof String){
                controlNumber = (String) obj;
            }
        }
        if (soapObject.hasProperty("DrawNumber"))
        {
            Object obj = soapObject.getProperty("DrawNumber");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                drawNumber = j.toString();
            }else if (obj!= null && obj instanceof String){
                drawNumber = (String) obj;
            }
        }
        if (soapObject.hasProperty("DrawDate"))
        {
            Object obj = soapObject.getProperty("DrawDate");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                drawDate = j.toString();
            }else if (obj!= null && obj instanceof String){
                drawDate = (String) obj;
            }
        }
        if (soapObject.hasProperty("Status"))
        {
            Object obj = soapObject.getProperty("Status");
            if (obj!= null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive)obj;
                status = ResponseStatus.fromString(j.toString());
            }
        }
        if (soapObject.hasProperty("ErrorDetail"))
        {
            Object obj = soapObject.getProperty("ErrorDetail");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                errorDetail = j.toString();
            }else if (obj!= null && obj instanceof String){
                errorDetail = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return ivuLoto;
            case 1:
                return controlNumber;
            case 2:
                return drawNumber;
            case 3:
                return drawDate;
            case 4:
                return status.toString();
            case 5:
                return errorDetail;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 6;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "IvuLoto";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ControlNumber";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "DrawNumber";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "DrawDate";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Status";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ErrorDetail";
                break;
        }
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
