package com.kaching123.tcr.websvc.api.prepaid;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 1/23/2015 11:16:22 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class MerchantFlags implements KvmSerializable {
    
    public boolean sunpassActivated;
    public boolean billPaymentActivated;
    public boolean direcTvPRActivated;
    public boolean iVULotoActivated;
    
    public MerchantFlags(){}
    
    public MerchantFlags(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("SunpassActivated"))
        {
            Object obj = soapObject.getProperty("SunpassActivated");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                sunpassActivated = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                sunpassActivated = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("BillPaymentActivated"))
        {
            Object obj = soapObject.getProperty("BillPaymentActivated");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                billPaymentActivated = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                billPaymentActivated = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("DirecTvPRActivated"))
        {
            Object obj = soapObject.getProperty("DirecTvPRActivated");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                direcTvPRActivated = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                direcTvPRActivated = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("IVULotoActivated"))
        {
            Object obj = soapObject.getProperty("IVULotoActivated");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                iVULotoActivated = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                iVULotoActivated = (Boolean) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return sunpassActivated;
            case 1:
                return billPaymentActivated;
            case 2:
                return direcTvPRActivated;
            case 3:
                return iVULotoActivated;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 2;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "SunpassActivated";
                break;
            case 1:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "BillPaymentActivated";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
