package com.kaching123.tcr.websvc.api.prepaid;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 3/4/2014 8:12:58 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.io.Serializable;
import java.util.Hashtable;

public class PaymentOption implements KvmSerializable, Serializable {
    
    public String paymentType;
    public double feeAmount;
    
    public PaymentOption(){}
    
    public PaymentOption(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("PaymentType"))
        {
            Object obj = soapObject.getProperty("PaymentType");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                paymentType = j.toString();
            }else if (obj!= null && obj instanceof String){
                paymentType = (String) obj;
            }
        }
        if (soapObject.hasProperty("FeeAmount"))
        {
            Object obj = soapObject.getProperty("FeeAmount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                feeAmount = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                feeAmount = (Double) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return paymentType;
            case 1:
                return feeAmount;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 2;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "PaymentType";
                break;
            case 1:
                info.type = Double.class;
                info.name = "FeeAmount";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }

    @Override
    public String toString() {
        return paymentType;
    }
}
