package com.kaching123.tcr.websvc.api.prepaid;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 11/6/2014 9:25:05 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.io.Serializable;
import java.util.Hashtable;

public class ProductRate implements KvmSerializable, Serializable {

    public String country;
    public double localRate;
    public double tollFreeRate;

    public ProductRate() {
    }

    public ProductRate(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("Country")) {
            Object obj = soapObject.getProperty("Country");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                country = j.toString();
            } else if (obj != null && obj instanceof String) {
                country = (String) obj;
            }
        }
        if (soapObject.hasProperty("LocalRate")) {
            Object obj = soapObject.getProperty("LocalRate");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                localRate = Double.parseDouble(j.toString());
            } else if (obj != null && obj instanceof Number) {
                localRate = (Double) obj;
            }
        }
        if (soapObject.hasProperty("TollFreeRate")) {
            Object obj = soapObject.getProperty("TollFreeRate");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                tollFreeRate = Double.parseDouble(j.toString());
            } else if (obj != null && obj instanceof Number) {
                tollFreeRate = (Double) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return country;
            case 1:
                return localRate;
            case 2:
                return tollFreeRate;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Country";
                break;
            case 1:
                info.type = Double.class;
                info.name = "LocalRate";
                break;
            case 2:
                info.type = Double.class;
                info.name = "TollFreeRate";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
