package com.kaching123.tcr.util;

import java.util.HashMap;

/**
 * Created by pkabakov on 21.03.14.
 */
public class CountryCodes {
    private static HashMap<String, String> countriesMap = new HashMap<String, String>();
    static {
        countriesMap.put("AF", "93");
        countriesMap.put("AFG", "93");
        countriesMap.put("AL", "355");
        countriesMap.put("ALB", "355");
        countriesMap.put("DZ", "213");
        countriesMap.put("DZA", "213");
        countriesMap.put("AS", "1 684");
        countriesMap.put("ASM", "1 684");
        countriesMap.put("AD", "376");
        countriesMap.put("AND", "376");
        countriesMap.put("AO", "244");
        countriesMap.put("AGO", "244");
        countriesMap.put("AI", "1 264");
        countriesMap.put("AIA", "1 264");
        countriesMap.put("AQ", "672");
        countriesMap.put("ATA", "672");
        countriesMap.put("AG", "1 268");
        countriesMap.put("ATG", "1 268");
        countriesMap.put("AR", "54");
        countriesMap.put("ARG", "54");
        countriesMap.put("AM", "374");
        countriesMap.put("ARM", "374");
        countriesMap.put("AW", "297");
        countriesMap.put("ABW", "297");
        countriesMap.put("AU", "61");
        countriesMap.put("AUS", "61");
        countriesMap.put("AT", "43");
        countriesMap.put("AUT", "43");
        countriesMap.put("AZ", "994");
        countriesMap.put("AZE", "994");
        countriesMap.put("BS", "1 242");
        countriesMap.put("BHS", "1 242");
        countriesMap.put("BH", "973");
        countriesMap.put("BHR", "973");
        countriesMap.put("BD", "880");
        countriesMap.put("BGD", "880");
        countriesMap.put("BB", "1 246");
        countriesMap.put("BRB", "1 246");
        countriesMap.put("BY", "375");
        countriesMap.put("BLR", "375");
        countriesMap.put("BE", "32");
        countriesMap.put("BEL", "32");
        countriesMap.put("BZ", "501");
        countriesMap.put("BLZ", "501");
        countriesMap.put("BJ", "229");
        countriesMap.put("BEN", "229");
        countriesMap.put("BM", "1 441");
        countriesMap.put("BMU", "1 441");
        countriesMap.put("BT", "975");
        countriesMap.put("BTN", "975");
        countriesMap.put("BO", "591");
        countriesMap.put("BOL", "591");
        countriesMap.put("BA", "387");
        countriesMap.put("BIH", "387");
        countriesMap.put("BW", "267");
        countriesMap.put("BWA", "267");
        countriesMap.put("BR", "55");
        countriesMap.put("BRA", "55");
        countriesMap.put("VG", "1 284");
        countriesMap.put("VGB", "1 284");
        countriesMap.put("BN", "673");
        countriesMap.put("BRN", "673");
        countriesMap.put("BG", "359");
        countriesMap.put("BGR", "359");
        countriesMap.put("BF", "226");
        countriesMap.put("BFA", "226");
        countriesMap.put("MM", "95");
        countriesMap.put("MMR", "95");
        countriesMap.put("BI", "257");
        countriesMap.put("BDI", "257");
        countriesMap.put("KH", "855");
        countriesMap.put("KHM", "855");
        countriesMap.put("CM", "237");
        countriesMap.put("CMR", "237");
        countriesMap.put("CA", "1");
        countriesMap.put("CAN", "1");
        countriesMap.put("CV", "238");
        countriesMap.put("CPV", "238");
        countriesMap.put("KY", "1 345");
        countriesMap.put("CYM", "1 345");
        countriesMap.put("CF", "236");
        countriesMap.put("CAF", "236");
        countriesMap.put("TD", "235");
        countriesMap.put("TCD", "235");
        countriesMap.put("CL", "56");
        countriesMap.put("CHL", "56");
        countriesMap.put("CN", "86");
        countriesMap.put("CHN", "86");
        countriesMap.put("CX", "61");
        countriesMap.put("CXR", "61");
        countriesMap.put("CC", "61");
        countriesMap.put("CCK", "61");
        countriesMap.put("CO", "57");
        countriesMap.put("COL", "57");
        countriesMap.put("KM", "269");
        countriesMap.put("COM", "269");
        countriesMap.put("CG", "242");
        countriesMap.put("COG", "242");
        countriesMap.put("CD", "243");
        countriesMap.put("COD", "243");
        countriesMap.put("CK", "682");
        countriesMap.put("COK", "682");
        countriesMap.put("CR", "506");
        countriesMap.put("CRC", "506");
        countriesMap.put("HR", "385");
        countriesMap.put("HRV", "385");
        countriesMap.put("CU", "53");
        countriesMap.put("CUB", "53");
        countriesMap.put("CY", "357");
        countriesMap.put("CYP", "357");
        countriesMap.put("CZ", "420");
        countriesMap.put("CZE", "420");
        countriesMap.put("DK", "45");
        countriesMap.put("DNK", "45");
        countriesMap.put("DJ", "253");
        countriesMap.put("DJI", "253");
        countriesMap.put("DM", "1 767");
        countriesMap.put("DMA", "1 767");
        countriesMap.put("DO", "1 809");
        countriesMap.put("DOM", "1 809");
        countriesMap.put("TL", "670");
        countriesMap.put("TLS", "670");
        countriesMap.put("EC", "593");
        countriesMap.put("ECU", "593");
        countriesMap.put("EG", "20");
        countriesMap.put("EGY", "20");
        countriesMap.put("SV", "503");
        countriesMap.put("SLV", "503");
        countriesMap.put("GQ", "240");
        countriesMap.put("GNQ", "240");
        countriesMap.put("ER", "291");
        countriesMap.put("ERI", "291");
        countriesMap.put("EE", "372");
        countriesMap.put("EST", "372");
        countriesMap.put("ET", "251");
        countriesMap.put("ETH", "251");
        countriesMap.put("FK", "500");
        countriesMap.put("FLK", "500");
        countriesMap.put("FO", "298");
        countriesMap.put("FRO", "298");
        countriesMap.put("FJ", "679");
        countriesMap.put("FJI", "679");
        countriesMap.put("FI", "358");
        countriesMap.put("FIN", "358");
        countriesMap.put("FR", "33");
        countriesMap.put("FRA", "33");
        countriesMap.put("PF", "689");
        countriesMap.put("PYF", "689");
        countriesMap.put("GA", "241");
        countriesMap.put("GAB", "241");
        countriesMap.put("GM", "220");
        countriesMap.put("GMB", "220");
        countriesMap.put("GE", "995");
        countriesMap.put("GEO", "995");
        countriesMap.put("DE", "49");
        countriesMap.put("DEU", "49");
        countriesMap.put("GH", "233");
        countriesMap.put("GHA", "233");
        countriesMap.put("GI", "350");
        countriesMap.put("GIB", "350");
        countriesMap.put("GR", "30");
        countriesMap.put("GRC", "30");
        countriesMap.put("GL", "299");
        countriesMap.put("GRL", "299");
        countriesMap.put("GD", "1 473");
        countriesMap.put("GRD", "1 473");
        countriesMap.put("GU", "1 671");
        countriesMap.put("GUM", "1 671");
        countriesMap.put("GT", "502");
        countriesMap.put("GTM", "502");
        countriesMap.put("GN", "224");
        countriesMap.put("GIN", "224");
        countriesMap.put("GW", "245");
        countriesMap.put("GNB", "245");
        countriesMap.put("GY", "592");
        countriesMap.put("GUY", "592");
        countriesMap.put("HT", "509");
        countriesMap.put("HTI", "509");
        countriesMap.put("HN", "504");
        countriesMap.put("HND", "504");
        countriesMap.put("HK", "852");
        countriesMap.put("HKG", "852");
        countriesMap.put("HU", "36");
        countriesMap.put("HUN", "36");
        countriesMap.put("IS", "354");
        countriesMap.put("IS", "354");
        countriesMap.put("IN", "91");
        countriesMap.put("IND", "91");
        countriesMap.put("ID", "62");
        countriesMap.put("IDN", "62");
        countriesMap.put("IR", "98");
        countriesMap.put("IRN", "98");
        countriesMap.put("IQ", "964");
        countriesMap.put("IRQ", "964");
        countriesMap.put("IE", "353");
        countriesMap.put("IRL", "353");
        countriesMap.put("IM", "44");
        countriesMap.put("IMN", "44");
        countriesMap.put("IL", "972");
        countriesMap.put("ISR", "972");
        countriesMap.put("IT", "39");
        countriesMap.put("ITA", "39");
        countriesMap.put("CI", "225");
        countriesMap.put("CIV", "225");
        countriesMap.put("JM", "1 876");
        countriesMap.put("JAM", "1 876");
        countriesMap.put("JP", "81");
        countriesMap.put("JPN", "81");
        countriesMap.put("JO", "962");
        countriesMap.put("JOR", "962");
        countriesMap.put("KZ", "7");
        countriesMap.put("KAZ", "7");
        countriesMap.put("KE", "254");
        countriesMap.put("KEN", "254");
        countriesMap.put("KI", "686");
        countriesMap.put("KIR", "686");
        countriesMap.put("KW", "965");
        countriesMap.put("KWT", "965");
        countriesMap.put("KG", "996");
        countriesMap.put("KGZ", "996");
        countriesMap.put("LA", "856");
        countriesMap.put("LAO", "856");
        countriesMap.put("LV", "371");
        countriesMap.put("LVA", "371");
        countriesMap.put("LB", "961");
        countriesMap.put("LBN", "961");
        countriesMap.put("LS", "266");
        countriesMap.put("LSO", "266");
        countriesMap.put("LR", "231");
        countriesMap.put("LBR", "231");
        countriesMap.put("LY", "218");
        countriesMap.put("LBY", "218");
        countriesMap.put("LI", "423");
        countriesMap.put("LIE", "423");
        countriesMap.put("LT", "370");
        countriesMap.put("LTU", "370");
        countriesMap.put("LU", "352");
        countriesMap.put("LUX", "352");
        countriesMap.put("MO", "853");
        countriesMap.put("MAC", "853");
        countriesMap.put("MK", "389");
        countriesMap.put("MKD", "389");
        countriesMap.put("MG", "261");
        countriesMap.put("MDG", "261");
        countriesMap.put("MW", "265");
        countriesMap.put("MWI", "265");
        countriesMap.put("MY", "60");
        countriesMap.put("MYS", "60");
        countriesMap.put("MV", "960");
        countriesMap.put("MDV", "960");
        countriesMap.put("ML", "223");
        countriesMap.put("MLI", "223");
        countriesMap.put("MT", "356");
        countriesMap.put("MLT", "356");
        countriesMap.put("MH", "692");
        countriesMap.put("MHL", "692");
        countriesMap.put("MR", "222");
        countriesMap.put("MRT", "222");
        countriesMap.put("MU", "230");
        countriesMap.put("MUS", "230");
        countriesMap.put("YT", "262");
        countriesMap.put("MYT", "262");
        countriesMap.put("MX", "52");
        countriesMap.put("MEX", "52");
        countriesMap.put("FM", "691");
        countriesMap.put("FSM", "691");
        countriesMap.put("MD", "373");
        countriesMap.put("MDA", "373");
        countriesMap.put("MC", "377");
        countriesMap.put("MCO", "377");
        countriesMap.put("MN", "976");
        countriesMap.put("MNG", "976");
        countriesMap.put("ME", "382");
        countriesMap.put("MNE", "382");
        countriesMap.put("MS", "1 664");
        countriesMap.put("MSR", "1 664");
        countriesMap.put("MA", "212");
        countriesMap.put("MAR", "212");
        countriesMap.put("MZ", "258");
        countriesMap.put("MOZ", "258");
        countriesMap.put("NA", "264");
        countriesMap.put("NAM", "264");
        countriesMap.put("NR", "674");
        countriesMap.put("NRU", "674");
        countriesMap.put("NP", "977");
        countriesMap.put("NPL", "977");
        countriesMap.put("NL", "31");
        countriesMap.put("NLD", "31");
        countriesMap.put("AN", "599");
        countriesMap.put("ANT", "599");
        countriesMap.put("NC", "687");
        countriesMap.put("NCL", "687");
        countriesMap.put("NZ", "64");
        countriesMap.put("NZL", "64");
        countriesMap.put("NI", "505");
        countriesMap.put("NIC", "505");
        countriesMap.put("NE", "227");
        countriesMap.put("NER", "227");
        countriesMap.put("NG", "234");
        countriesMap.put("NGA", "234");
        countriesMap.put("NU", "683");
        countriesMap.put("NIU", "683");
        countriesMap.put("NFK", "672");
        countriesMap.put("MP", "1 670");
        countriesMap.put("MNP", "1 670");
        countriesMap.put("KP", "850");
        countriesMap.put("PRK", "850");
        countriesMap.put("NO", "47");
        countriesMap.put("NOR", "47");
        countriesMap.put("OM", "968");
        countriesMap.put("OMN", "968");
        countriesMap.put("PK", "92");
        countriesMap.put("PAK", "92");
        countriesMap.put("PW", "680");
        countriesMap.put("PLW", "680");
        countriesMap.put("PA", "507");
        countriesMap.put("PAN", "507");
        countriesMap.put("PG", "675");
        countriesMap.put("PNG", "675");
        countriesMap.put("PY", "595");
        countriesMap.put("PRY", "595");
        countriesMap.put("PE", "51");
        countriesMap.put("PER", "51");
        countriesMap.put("PH", "63");
        countriesMap.put("PHL", "63");
        countriesMap.put("PN", "870");
        countriesMap.put("PCN", "870");
        countriesMap.put("PL", "48");
        countriesMap.put("POL", "48");
        countriesMap.put("PT", "351");
        countriesMap.put("PRT", "351");
        countriesMap.put("PR", "1");
        countriesMap.put("PRI", "1");
        countriesMap.put("QA", "974");
        countriesMap.put("QAT", "974");
        countriesMap.put("RO", "40");
        countriesMap.put("ROU", "40");
        countriesMap.put("RU", "7");
        countriesMap.put("RUS", "7");
        countriesMap.put("RW", "250");
        countriesMap.put("RWA", "250");
        countriesMap.put("BL", "590");
        countriesMap.put("BLM", "590");
        countriesMap.put("WS", "685");
        countriesMap.put("WSM", "685");
        countriesMap.put("SM", "378");
        countriesMap.put("SMR", "378");
        countriesMap.put("ST", "239");
        countriesMap.put("STP", "239");
        countriesMap.put("SA", "966");
        countriesMap.put("SAU", "966");
        countriesMap.put("SN", "221");
        countriesMap.put("SEN", "221");
        countriesMap.put("RS", "381");
        countriesMap.put("SRB", "381");
        countriesMap.put("SC", "248");
        countriesMap.put("SYC", "248");
        countriesMap.put("SL", "232");
        countriesMap.put("SLE", "232");
        countriesMap.put("SG", "65");
        countriesMap.put("SGP", "65");
        countriesMap.put("SK", "421");
        countriesMap.put("SVK", "421");
        countriesMap.put("SI", "386");
        countriesMap.put("SVN", "386");
        countriesMap.put("SB", "677");
        countriesMap.put("SLB", "677");
        countriesMap.put("SO", "252");
        countriesMap.put("SOM", "252");
        countriesMap.put("ZA", "27");
        countriesMap.put("ZAF", "27");
        countriesMap.put("KR", "82");
        countriesMap.put("KOR", "82");
        countriesMap.put("ES", "34");
        countriesMap.put("ESP", "34");
        countriesMap.put("LK", "94");
        countriesMap.put("LKA", "94");
        countriesMap.put("SH", "290");
        countriesMap.put("SHN", "290");
        countriesMap.put("KN", "1 869");
        countriesMap.put("KNA", "1 869");
        countriesMap.put("LC", "1 758");
        countriesMap.put("LCA", "1 758");
        countriesMap.put("MF", "1 599");
        countriesMap.put("MAF", "1 599");
        countriesMap.put("PM", "508");
        countriesMap.put("SPM", "508");
        countriesMap.put("VC", "1 784");
        countriesMap.put("VCT", "1 784");
        countriesMap.put("SD", "249");
        countriesMap.put("SDN", "249");
        countriesMap.put("SR", "597");
        countriesMap.put("SUR", "597");
        countriesMap.put("SZ", "268");
        countriesMap.put("SWZ", "268");
        countriesMap.put("SE", "46");
        countriesMap.put("SWE", "46");
        countriesMap.put("CH", "41");
        countriesMap.put("CHE", "41");
        countriesMap.put("SY", "963");
        countriesMap.put("SYR", "963");
        countriesMap.put("TW", "886");
        countriesMap.put("TWN", "886");
        countriesMap.put("TJ", "992");
        countriesMap.put("TJK", "992");
        countriesMap.put("TZ", "255");
        countriesMap.put("TZA", "255");
        countriesMap.put("TH", "66");
        countriesMap.put("THA", "66");
        countriesMap.put("TG", "228");
        countriesMap.put("TGO", "228");
        countriesMap.put("TK", "690");
        countriesMap.put("TKL", "690");
        countriesMap.put("TO", "676");
        countriesMap.put("TON", "676");
        countriesMap.put("TT", "1 868");
        countriesMap.put("TTO", "1 868");
        countriesMap.put("TN", "216");
        countriesMap.put("TUN", "216");
        countriesMap.put("TR", "90");
        countriesMap.put("TUR", "90");
        countriesMap.put("TM", "993");
        countriesMap.put("TKM", "993");
        countriesMap.put("TC", "1 649");
        countriesMap.put("TCA", "1 649");
        countriesMap.put("TV", "688");
        countriesMap.put("TUV", "688");
        countriesMap.put("AE", "971");
        countriesMap.put("ARE", "971");
        countriesMap.put("UG", "256");
        countriesMap.put("UGA", "256");
        countriesMap.put("GB", "44");
        countriesMap.put("GBR", "44");
        countriesMap.put("UA", "380");
        countriesMap.put("UKR", "380");
        countriesMap.put("UY", "598");
        countriesMap.put("URY", "598");
        countriesMap.put("US", "1");
        countriesMap.put("USA", "1");
        countriesMap.put("UZ", "998");
        countriesMap.put("UZB", "998");
        countriesMap.put("VU", "678");
        countriesMap.put("VUT", "678");
        countriesMap.put("VA", "39");
        countriesMap.put("VAT", "39");
        countriesMap.put("VE", "58");
        countriesMap.put("VEN", "58");
        countriesMap.put("VN", "84");
        countriesMap.put("VNM", "84");
        countriesMap.put("VI", "1 340");
        countriesMap.put("VIR", "1 340");
        countriesMap.put("WF", "681");
        countriesMap.put("WLF", "681");
        countriesMap.put("YE", "967");
        countriesMap.put("YEM", "967");
        countriesMap.put("ZM", "260");
        countriesMap.put("ZMB", "260");
        countriesMap.put("ZW", "263");
        countriesMap.put("ZWE", "263");
    }

    public static String getPhoneCode(String code) {
        return countriesMap.get(code);
    }

}
